### PR TITLE
Tidy up code

### PR DESCRIPTION
**Pull request by bonzer35**
Removed 0's and 1's

### CODE REVIEW

**Comment by futurexdesign** [comment]
@bonzer35 Isn't this change already in main? Why does it need merged back to `sounder_for_review`?

**Comment by bonzer35** [comment]
You requested some remnants of zeros and ones to be removed and replaced by
true/false, so I did that.

**Comment by futurexdesign** [comment]
@bonzer35 Take a look at the changes listed in this PR, thats not what is in here, this contains your timer bug fix, and nothing else

**Comment by bonzer35** [comment]
Ok, will take  a look later

**Comment by bonzer35** [comment]
> @bonzer35 Take a look at the changes listed in this PR, thats not what is in here, this contains your timer bug fix, and nothing else

That's strange. commit 3bd5f19 contains the removal of zeros and ones and this one shows the UI fix, but the UI fix should be in its own branch, not 'sounder_for_review'. When I checkout my local sounder_for_review, the UI changes have not been done in MotorControl, which is what I would expect. And where is UI_fix in the branch list? I'm confused.

**Comment by futurexdesign** [comment]
The UI Fix was merged previously.   It doesn't need to be merged into the sounder branch, as it already exists in main.   https://github.com/futurexdesign/KiwiBoardFirmware/commit/3bd5f196c5445350ed4a9b9ae2bafa9be28ef409 already exists in your branch

**Pull request closed without merging**
